import React from 'react';
import { TrendingUp, FileText, BarChart2, Info } from 'lucide-react';

export default function HistoricalAnalytics() {
  return (
    <div className="space-y-6">
      {/* Description */}
      <div className="p-6 rounded-2xl bg-[#161925] border border-[#222533] flex items-start gap-4">
        <div className="p-3 rounded-xl bg-blue-500/10 text-blue-400 mt-1">
          <Info className="w-5 h-5" />
        </div>
        <div>
          <h3 className="text-sm font-bold text-slate-100">R Multiple Linear Regression Traffic Forecasting</h3>
          <p className="text-xs text-slate-400 mt-1 leading-relaxed">
            Traffic analytics are generated via an R statistical model analyzing relationship variables (`TimeOfDay` and `ActiveIPs`) to forecast network volume and predict potential infrastructure congestion.
          </p>
        </div>
      </div>

      {/* R Plot Display */}
      <div className="p-6 rounded-2xl bg-[#161925] border border-[#222533] flex flex-col items-center">
        <div className="w-full flex items-center justify-between mb-4">
          <h3 className="text-sm font-bold text-slate-100">Traffic Volume Forecast Plot (Generated by R)</h3>
          <span className="text-xs font-mono text-slate-400 px-3 py-1 rounded bg-[#1a1d2b]">
            traffic_forecast.png
          </span>
        </div>

        <div className="w-full rounded-xl overflow-hidden border border-[#2e3244] bg-black/40 flex items-center justify-center p-2">
          <img 
            src="/traffic_forecast.png" 
            alt="Traffic Forecast R Plot" 
            className="max-w-full h-auto rounded-lg shadow-lg"
            onError={(e) => {
              e.target.style.display = 'none';
            }}
          />
        </div>
      </div>
    </div>
  );
}
